### ISSUE TITLE
Batching

### ISSUE THREAD

**Issue by olizilla** [web3-storage/pickup#13]
We have the worst possible scaling set up right now. 1 request -> 1 worker node. 0 parallelisation or batching. It's dial-a-kubo. Each request gets it's own kubo, and doesn't let go until the request is done or we timeout.

We can process messages in batches of ~5, limited by the 200GB storage max in fargate currently.

TODO
- [ ] implement `handleMessageBatch` - https://github.com/bbc/sqs-consumer#options
- [ ] port PR for acknowledging partial batches where some failed - https://github.com/bbc/sqs-consumer/pull/255

**Comment by codeflyer** [comment]
Closed with PR: https://github.com/web3-storage/pickup/pull/73
