### ISSUE TITLE
Add handler for `GET /pins?cids=baf1,...,bafN`

### ISSUE THREAD

**Issue by olizilla** [web3-storage/pickup#63]
we need to handle batch pin status requests where the list of CIDs to check are passed as a comma separated string of cids under the key `cids` in the URLSearchParams

it's used by the cron-pins scheduled task that runs regularly to poll cluster to see if the pins that were previously Queued are have changed state yet via the cluster client lib `cluster.statusAll`

- cron-pins job where it is called via `cluster.statusAll` - https://github.com/web3-storage/web3.storage/blob/272c83b860c5d15a48c05d3cedb2063b26ca8abe/packages/cron/src/jobs/pins.js#L174
- the implementation of `cluster.statusAll` - https://github.com/nftstorage/ipfs-cluster/blob/02a4c1d0f4cbe86557abd738be83bb2de25ccec0/src/index.js#L189

**Comment by olizilla** [comment]
This is deployed to staging but currently throws an error if more than 1 CID is passed as the `cids` search param.

**Comment by codeflyer** [comment]
As discussed, the issue was due a timeout in the lambda.

the deploy was set to a 10 second value. Moved it to 60 seconds to be sure. 
The bottleneck is in the cluster, we don't have control on it. 

The pickup performance instead are really fast.

**Comment by olizilla** [comment]
@codeflyer the aws http gateway times out after 30s max waiting for a lambda to respond. 
https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#http-api-quotas

We can probably set the lambda timeout to 31s. the request will have already been closed if it takes longer.
